# .github/workflows/daily-airtable-update.yml
name: Daily Airtable Data Update

on:
  schedule:
    # רץ כל יום ב-9:00 בבוקר שעון ישראל (6:00 UTC)
    - cron: '0 6 * * *'
  
  # אפשרות להפעיל ידנית
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install node-fetch@2
    
    - name: Fetch and process Airtable data
      env:
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      run: node scripts/fetch-airtable-data.js
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        
        # בדיקה אם יש שינויים
        if [[ -n $(git status -s) ]]; then
          git add data/daily-donations.json
          git commit -m "📊 Daily update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
          echo "✅ Data updated successfully"
        else
          echo "ℹ️ No changes detected"
        fi
